name: Update Cherry Plot

on:
  schedule:
    - cron: '0 16 * * 6'  # Saturday 18:00 CEST
  workflow_dispatch:     # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install gdown pandas numpy plotly python-docx matplotlib

      # Python handles the gdown natively inside its working-directory
      - name: Run script
        working-directory: ./Cherry_plot_updater
        run: python cherry_plot_update.py

      - name: Upload plot to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./Cherry_plot_updater/
          server-dir: /public_html/
          exclude: |
            **/*
            !cherry_growth_data.html
