name: Update Cherry Plot

on:
  schedule:
    - cron: '0 7 * * 1'  # Every Monday at 07:00 UTC
  workflow_dispatch:     # Also allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install gdown pandas numpy plotly python-docx

      - name: Download berekeningen.docx from Google Drive
        run: |
          gdown --id 1EdVCBcDVvejNhifkps9n132LYgLStyjv -O berekeningen.docx

      - name: Run script
        run: python main.py

      - name: Upload plot to FTP
        uses: sebastianpopp/ftp-action@v1
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          localDir: ./
          remoteDir: /public_html/path/to/your/plot